export const GET_CUSTOMER_START = 'GET_CUSTOMER_START'
export const GET_CUSTOMER_SUCCESS = 'GET_CUSTOMER_SUCCESS'
export const GET_CUSTOMER_FAIL = 'GET_CUSTOMER_FAIL'

export const CREATE_CUSTOMER_START = 'CREATE_CUSTOMER_START'
export const CREATE_CUSTOMER_SUCCESS = 'CREATE_CUSTOMER_SUCCESS'
export const CREATE_CUSTOMER_FAIL = 'CREATE_CUSTOMER_FAIL'

export const ADD_ADDRESS_START = 'ADD_ADDRESS_START'
export const ADD_ADDRESS_SUCCESS = 'ADD_ADDRESS_SUCCESS'
export const ADD_ADDRESS_FAIL = 'ADD_ADDRESS_FAIL'

export const SHOW_ADD_CUSTOMER_MODAL = 'SHOW_ADD_CUSTOMER_MODAL'
export const CLOSE_ADD_CUSTOMER_MODAL = 'CLOSE_ADD_CUSTOMER_MODAL'

export const SHOW_ADD_ADDRESS_MODAL = 'SHOW_ADD_ADDRESS_MODAL'
export const CLOSE_ADD_ADDRESS_MODAL = 'CLOSE_ADD_ADDRESS_MODAL'

export const UPDATE_CREATE_SALE = 'UPDATE_CREATE_SALE'
export const CREATE_SALE_START = 'CREATE_SALE_START'
export const CREATE_SALE_SUCCESS = 'CREATE_SALE_SUCCESS'
export const CREATE_SALE_FAIL = 'CREATE_SALE_FAIL'
export const ADD_PRODUCT_TO_BILL = 'ADD_PRODUCT_TO_BILL'
export const REMOVE_PRODUCT_FROM_BILL = 'REMOVE_PRODUCT_FROM_BILL'
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'

export const GET_PRODUCTS_START = 'GET_PRODUCTS_START'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL'

export const SET_ACTIVE_PRODUCT = 'SET_ACTIVE_PRODUCT'
export const UPDATE_DEFAULT_COMBINATION = 'UPDATE_DEFAULT_COMBINATION'

export const CLOSE_NOTIFICATION =  'CLOSE_NOTIFICATION'